### ISSUE TITLE
Manuelly enter ticket template id

### ISSUE THREAD

**Issue by elmarbransch** [cloudogu/bugshot#6]
Hi there, 

great companion for redmine, many thanks for providing it.

Our Redmine is slightly modified and it does not show the bugshot context menu entry.
I guess it will simply store the issue id somewhere? Is there a way I can unpack the extension, enter the id and load it as a dev extension? I did not find the right place in the code so far to start.
Additionally: why not let the user enter the ticket id manually?
many thanks
-Elmar

**Comment by eheimbuch** [comment]
Hey and thanks for reaching out.

May i ask which version of Redmine you are using and why it does not work?

For your first question you can check out the [readme](https://github.com/cloudogu/bugshot#readme) of this project. You should be able to clone this project and make the develop version run on your chrome browser by following the instructions.

Making the user add the issue id manually should also be possible. Since the bugshot ui have no page for templates we simply not added it yet. The templates are managed [here](https://github.com/cloudogu/bugshot/blob/2281de1f2d6e74e269ecbecf9f7b3b94df4eb6c5/src/api/store.ts#L52) using the [chrome store api](https://github.com/cloudogu/bugshot/blob/2281de1f2d6e74e269ecbecf9f7b3b94df4eb6c5/src/api/store.ts#L17).

Feel free to create a pull request. :)

**Comment by elmarbransch** [comment]
thanks for the prompt reply :)

Already found, that our Redmine (Redmine-X) has a different theme and lacks the selector used in the code here:
https://github.com/cloudogu/bugshot/blob/2281de1f2d6e74e269ecbecf9f7b3b94df4eb6c5/src/content.ts#L70

For now I should be able to adjust the selector and re-deploy locally.

Thanks again!

**Comment by elmarbransch** [comment]
got it to work by using some existing selector in our theme :)
<img width="727" alt="image" src="https://github.com/cloudogu/bugshot/assets/736528/730d5752-80bd-4015-97c0-2551d71cb16c">

Can't promise, if I can manage to create a pull request - would be a good exercise for me :)
